---
name: composeflux
services:
  composeflux:
    build: .
    container_name: composeflux
    environment:
      # Reconciler Configuration
      SECRETS_PROVIDER: ${SECRETS_PROVIDER}
      STACK_PATH: ${STACK_PATH}
      # CONFIG_FILE: stack.yml
      # GIT_INTERVAL: 5m
      # IMAGE_UPDATE_SCHEDULE: ""

      # Git Source Configuration
      GIT_REPO_URL: ${GIT_REPO_URL}
      GIT_DEPLOY_KEY_SECRET_REF: ${GIT_DEPLOY_KEY_SECRET_REF}
      GIT_BRANCH: ${GIT_BRANCH}
      # GIT_CLONE_PATH: /opt/compose-stack
      GIT_SSH_KEY_PATH: ${GIT_SSH_KEY_PATH}

      # Logging
      LOG_ADD_SOURCE: ${LOG_ADD_SOURCE}
      LOG_LEVEL: ${LOG_LEVEL}

      # Bitwarden Secrets Manager
      BITWARDEN_ACCESS_TOKEN: ${BITWARDEN_ACCESS_TOKEN}
      BITWARDEN_ORGANIZATION_ID: ${BITWARDEN_ORGANIZATION_ID}
      BITWARDEN_PROJECT_ID: ${BITWARDEN_PROJECT_ID}
      # BITWARDEN_API_URL: https://vault.bitwarden.com/api
      # BITWARDEN_IDENTITY_URL: https://vault.bitwarden.com/identity

      # Infisical Secrets Manager
      # INFISICAL_CLIENT_ID: ${INFISICAL_CLIENT_ID}
      # INFISICAL_CLIENT_SECRET: ${INFISICAL_CLIENT_SECRET}
      # INFISICAL_ENVIRONMENT: ${INFISICAL_ENVIRONMENT}
      # INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
      # INFISICAL_SECRET_PATH: /
      # INFISICAL_SITE_URL: https://app.infisical.com
    hostname: composeflux
    ports:
      - 9090:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/.ssh/composeflux_id_rsa:/tmp/composeflux_id_rsa
      - compose-stack:/opt/compose-stack
volumes:
  compose-stack:
    name: compose-stack
