---
name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Dockerfile"
      - ".github/workflows/ci.yml"
      - ".github/workflows/docker-build-push.yml"

jobs:
  golangci-lint:
    name: Lint Source Code
    runs-on: ubuntu-slim
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Run Linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          working-directory: ./
          args: --timeout 5m

  docker-build:
    name: Build & Push Dev Image
    if: contains(github.event.pull_request.labels.*.name, 'build')
    needs: golangci-lint
    uses: ./.github/workflows/docker-build-push.yml
    permissions:
      contents: read
      packages: write
    with:
      push: true
      tags: ghcr.io/${{ github.repository }}:dev
