---
name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  docker-build-push:
    name: Build & Push Release Images
    uses: ./.github/workflows/docker-build-push.yml
    permissions:
      contents: read
      packages: write
    with:
      push: true
      tags: |
        ghcr.io/${{ github.repository }}:latest
        ghcr.io/${{ github.repository }}:${{ github.ref_name }}
